# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tku_msgs/HSVValue.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HSVValue(genpy.Message):
  _md5sum = "a3f516b6603d2233bee0097ee5df3644"
  _type = "tku_msgs/HSVValue"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 HMin
int16 HMax
int16 SMin
int16 SMax
int16 VMin
int16 VMax

"""
  __slots__ = ['HMin','HMax','SMin','SMax','VMin','VMax']
  _slot_types = ['int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       HMin,HMax,SMin,SMax,VMin,VMax

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HSVValue, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.HMin is None:
        self.HMin = 0
      if self.HMax is None:
        self.HMax = 0
      if self.SMin is None:
        self.SMin = 0
      if self.SMax is None:
        self.SMax = 0
      if self.VMin is None:
        self.VMin = 0
      if self.VMax is None:
        self.VMax = 0
    else:
      self.HMin = 0
      self.HMax = 0
      self.SMin = 0
      self.SMax = 0
      self.VMin = 0
      self.VMax = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6h().pack(_x.HMin, _x.HMax, _x.SMin, _x.SMax, _x.VMin, _x.VMax))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.HMin, _x.HMax, _x.SMin, _x.SMax, _x.VMin, _x.VMax,) = _get_struct_6h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6h().pack(_x.HMin, _x.HMax, _x.SMin, _x.SMax, _x.VMin, _x.VMax))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.HMin, _x.HMax, _x.SMin, _x.SMax, _x.VMin, _x.VMax,) = _get_struct_6h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6h = None
def _get_struct_6h():
    global _struct_6h
    if _struct_6h is None:
        _struct_6h = struct.Struct("<6h")
    return _struct_6h
