# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tku_msgs/LineData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tku_msgs.msg

class LineData(genpy.Message):
  _md5sum = "a197ca641f926ac7ce375913296b27d5"
  _type = "tku_msgs/LineData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 angle
int16 length
Cooridinate start_point
Cooridinate end_point
Cooridinate center_point

================================================================================
MSG: tku_msgs/Cooridinate
int16 x
int16 y
"""
  __slots__ = ['angle','length','start_point','end_point','center_point']
  _slot_types = ['float32','int16','tku_msgs/Cooridinate','tku_msgs/Cooridinate','tku_msgs/Cooridinate']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       angle,length,start_point,end_point,center_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LineData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.angle is None:
        self.angle = 0.
      if self.length is None:
        self.length = 0
      if self.start_point is None:
        self.start_point = tku_msgs.msg.Cooridinate()
      if self.end_point is None:
        self.end_point = tku_msgs.msg.Cooridinate()
      if self.center_point is None:
        self.center_point = tku_msgs.msg.Cooridinate()
    else:
      self.angle = 0.
      self.length = 0
      self.start_point = tku_msgs.msg.Cooridinate()
      self.end_point = tku_msgs.msg.Cooridinate()
      self.center_point = tku_msgs.msg.Cooridinate()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_f7h().pack(_x.angle, _x.length, _x.start_point.x, _x.start_point.y, _x.end_point.x, _x.end_point.y, _x.center_point.x, _x.center_point.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_point is None:
        self.start_point = tku_msgs.msg.Cooridinate()
      if self.end_point is None:
        self.end_point = tku_msgs.msg.Cooridinate()
      if self.center_point is None:
        self.center_point = tku_msgs.msg.Cooridinate()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.angle, _x.length, _x.start_point.x, _x.start_point.y, _x.end_point.x, _x.end_point.y, _x.center_point.x, _x.center_point.y,) = _get_struct_f7h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_f7h().pack(_x.angle, _x.length, _x.start_point.x, _x.start_point.y, _x.end_point.x, _x.end_point.y, _x.center_point.x, _x.center_point.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_point is None:
        self.start_point = tku_msgs.msg.Cooridinate()
      if self.end_point is None:
        self.end_point = tku_msgs.msg.Cooridinate()
      if self.center_point is None:
        self.center_point = tku_msgs.msg.Cooridinate()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.angle, _x.length, _x.start_point.x, _x.start_point.y, _x.end_point.x, _x.end_point.y, _x.center_point.x, _x.center_point.y,) = _get_struct_f7h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f7h = None
def _get_struct_f7h():
    global _struct_f7h
    if _struct_f7h is None:
        _struct_f7h = struct.Struct("<f7h")
    return _struct_f7h
