# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tku_msgs/PIDpackage.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PIDpackage(genpy.Message):
  _md5sum = "f5af5d5808f08141dacc4cc0d9857989"
  _type = "tku_msgs/PIDpackage"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 motor_P
int16 motor_I
int16 motor_D
bool  Pflag
bool  Iflag
bool  Dflag
int16 motorID
"""
  __slots__ = ['motor_P','motor_I','motor_D','Pflag','Iflag','Dflag','motorID']
  _slot_types = ['int16','int16','int16','bool','bool','bool','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motor_P,motor_I,motor_D,Pflag,Iflag,Dflag,motorID

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PIDpackage, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.motor_P is None:
        self.motor_P = 0
      if self.motor_I is None:
        self.motor_I = 0
      if self.motor_D is None:
        self.motor_D = 0
      if self.Pflag is None:
        self.Pflag = False
      if self.Iflag is None:
        self.Iflag = False
      if self.Dflag is None:
        self.Dflag = False
      if self.motorID is None:
        self.motorID = 0
    else:
      self.motor_P = 0
      self.motor_I = 0
      self.motor_D = 0
      self.Pflag = False
      self.Iflag = False
      self.Dflag = False
      self.motorID = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3h3Bh().pack(_x.motor_P, _x.motor_I, _x.motor_D, _x.Pflag, _x.Iflag, _x.Dflag, _x.motorID))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.motor_P, _x.motor_I, _x.motor_D, _x.Pflag, _x.Iflag, _x.Dflag, _x.motorID,) = _get_struct_3h3Bh().unpack(str[start:end])
      self.Pflag = bool(self.Pflag)
      self.Iflag = bool(self.Iflag)
      self.Dflag = bool(self.Dflag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3h3Bh().pack(_x.motor_P, _x.motor_I, _x.motor_D, _x.Pflag, _x.Iflag, _x.Dflag, _x.motorID))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.motor_P, _x.motor_I, _x.motor_D, _x.Pflag, _x.Iflag, _x.Dflag, _x.motorID,) = _get_struct_3h3Bh().unpack(str[start:end])
      self.Pflag = bool(self.Pflag)
      self.Iflag = bool(self.Iflag)
      self.Dflag = bool(self.Dflag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3h3Bh = None
def _get_struct_3h3Bh():
    global _struct_3h3Bh
    if _struct_3h3Bh is None:
        _struct_3h3Bh = struct.Struct("<3h3Bh")
    return _struct_3h3Bh
