(cl:in-package tku_msgs-srv)
(cl:export '(MODE-VAL
          MODE
          X_SWING_RANGE-VAL
          X_SWING_RANGE
          Y_SWING_RANGE-VAL
          Y_SWING_RANGE
          Z_SWING_RANGE-VAL
          Z_SWING_RANGE
          PERIOD_T-VAL
          PERIOD_T
          PERIOD_T2-VAL
          PERIOD_T2
          SAMPLE_TIME-VAL
          SAMPLE_TIME
          OSC_LOCKRANGE-VAL
          OSC_LOCKRANGE
          BASE_DEFAULT_Z-VAL
          BASE_DEFAULT_Z
          Y_SWING_SHIFT-VAL
          Y_SWING_SHIFT
          X_SWING_COM-VAL
          X_SWING_COM
          BASE_LIFT_Z-VAL
          BASE_LIFT_Z
          B_SPLINEPARAM-VAL
          B_SPLINEPARAM
          STAND_BALANCE-VAL
          STAND_BALANCE
))