(cl:defpackage tku_msgs-srv
  (:use )
  (:export
   "BUILDMODEL"
   "<BUILDMODEL-REQUEST>"
   "BUILDMODEL-REQUEST"
   "<BUILDMODEL-RESPONSE>"
   "BUILDMODEL-RESPONSE"
   "HSVINFO"
   "<HSVINFO-REQUEST>"
   "HSVINFO-REQUEST"
   "<HSVINFO-RESPONSE>"
   "HSVINFO-RESPONSE"
   "SAVEHSV"
   "<SAVEHSV-REQUEST>"
   "SAVEHSV-REQUEST"
   "<SAVEHSV-RESPONSE>"
   "SAVEHSV-RESPONSE"
  ))

