// Generated by gencpp from file tku_msgs/BuildModel.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_BUILDMODEL_H
#define TKU_MSGS_MESSAGE_BUILDMODEL_H

#include <ros/service_traits.h>


#include <tku_msgs/BuildModelRequest.h>
#include <tku_msgs/BuildModelResponse.h>


namespace tku_msgs
{

struct BuildModel
{

typedef BuildModelRequest Request;
typedef BuildModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BuildModel
} // namespace tku_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tku_msgs::BuildModel > {
  static const char* value()
  {
    return "80f5dbb159ea8995dfd77b0524c4dc6d";
  }

  static const char* value(const ::tku_msgs::BuildModel&) { return value(); }
};

template<>
struct DataType< ::tku_msgs::BuildModel > {
  static const char* value()
  {
    return "tku_msgs/BuildModel";
  }

  static const char* value(const ::tku_msgs::BuildModel&) { return value(); }
};


// service_traits::MD5Sum< ::tku_msgs::BuildModelRequest> should match
// service_traits::MD5Sum< ::tku_msgs::BuildModel >
template<>
struct MD5Sum< ::tku_msgs::BuildModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::BuildModel >::value();
  }
  static const char* value(const ::tku_msgs::BuildModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::BuildModelRequest> should match
// service_traits::DataType< ::tku_msgs::BuildModel >
template<>
struct DataType< ::tku_msgs::BuildModelRequest>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::BuildModel >::value();
  }
  static const char* value(const ::tku_msgs::BuildModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tku_msgs::BuildModelResponse> should match
// service_traits::MD5Sum< ::tku_msgs::BuildModel >
template<>
struct MD5Sum< ::tku_msgs::BuildModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::BuildModel >::value();
  }
  static const char* value(const ::tku_msgs::BuildModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::BuildModelResponse> should match
// service_traits::DataType< ::tku_msgs::BuildModel >
template<>
struct DataType< ::tku_msgs::BuildModelResponse>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::BuildModel >::value();
  }
  static const char* value(const ::tku_msgs::BuildModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TKU_MSGS_MESSAGE_BUILDMODEL_H
