// Generated by gencpp from file tku_msgs/CameraId.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_CAMERAID_H
#define TKU_MSGS_MESSAGE_CAMERAID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct CameraId_
{
  typedef CameraId_<ContainerAllocator> Type;

  CameraId_()
    : checkcameraid(false)
    , cameraid(0)  {
    }
  CameraId_(const ContainerAllocator& _alloc)
    : checkcameraid(false)
    , cameraid(0)  {
  (void)_alloc;
    }



   typedef uint8_t _checkcameraid_type;
  _checkcameraid_type checkcameraid;

   typedef int16_t _cameraid_type;
  _cameraid_type cameraid;





  typedef boost::shared_ptr< ::tku_msgs::CameraId_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::CameraId_<ContainerAllocator> const> ConstPtr;

}; // struct CameraId_

typedef ::tku_msgs::CameraId_<std::allocator<void> > CameraId;

typedef boost::shared_ptr< ::tku_msgs::CameraId > CameraIdPtr;
typedef boost::shared_ptr< ::tku_msgs::CameraId const> CameraIdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::CameraId_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::CameraId_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::CameraId_<ContainerAllocator1> & lhs, const ::tku_msgs::CameraId_<ContainerAllocator2> & rhs)
{
  return lhs.checkcameraid == rhs.checkcameraid &&
    lhs.cameraid == rhs.cameraid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::CameraId_<ContainerAllocator1> & lhs, const ::tku_msgs::CameraId_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::CameraId_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::CameraId_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::CameraId_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::CameraId_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::CameraId_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::CameraId_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::CameraId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cc97f36ddee60a3976eec15137b52b9";
  }

  static const char* value(const ::tku_msgs::CameraId_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cc97f36ddee60a3ULL;
  static const uint64_t static_value2 = 0x976eec15137b52b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::CameraId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/CameraId";
  }

  static const char* value(const ::tku_msgs::CameraId_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::CameraId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool checkcameraid\n"
"int16 cameraid\n"
;
  }

  static const char* value(const ::tku_msgs::CameraId_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::CameraId_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.checkcameraid);
      stream.next(m.cameraid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraId_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::CameraId_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::CameraId_<ContainerAllocator>& v)
  {
    s << indent << "checkcameraid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.checkcameraid);
    s << indent << "cameraid: ";
    Printer<int16_t>::stream(s, indent + "  ", v.cameraid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_CAMERAID_H
