// Generated by gencpp from file tku_msgs/CheckSector.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_CHECKSECTOR_H
#define TKU_MSGS_MESSAGE_CHECKSECTOR_H

#include <ros/service_traits.h>


#include <tku_msgs/CheckSectorRequest.h>
#include <tku_msgs/CheckSectorResponse.h>


namespace tku_msgs
{

struct CheckSector
{

typedef CheckSectorRequest Request;
typedef CheckSectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckSector
} // namespace tku_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tku_msgs::CheckSector > {
  static const char* value()
  {
    return "7ada61dc8c52272ee0201006887d39b5";
  }

  static const char* value(const ::tku_msgs::CheckSector&) { return value(); }
};

template<>
struct DataType< ::tku_msgs::CheckSector > {
  static const char* value()
  {
    return "tku_msgs/CheckSector";
  }

  static const char* value(const ::tku_msgs::CheckSector&) { return value(); }
};


// service_traits::MD5Sum< ::tku_msgs::CheckSectorRequest> should match
// service_traits::MD5Sum< ::tku_msgs::CheckSector >
template<>
struct MD5Sum< ::tku_msgs::CheckSectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::CheckSector >::value();
  }
  static const char* value(const ::tku_msgs::CheckSectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::CheckSectorRequest> should match
// service_traits::DataType< ::tku_msgs::CheckSector >
template<>
struct DataType< ::tku_msgs::CheckSectorRequest>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::CheckSector >::value();
  }
  static const char* value(const ::tku_msgs::CheckSectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tku_msgs::CheckSectorResponse> should match
// service_traits::MD5Sum< ::tku_msgs::CheckSector >
template<>
struct MD5Sum< ::tku_msgs::CheckSectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::CheckSector >::value();
  }
  static const char* value(const ::tku_msgs::CheckSectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::CheckSectorResponse> should match
// service_traits::DataType< ::tku_msgs::CheckSector >
template<>
struct DataType< ::tku_msgs::CheckSectorResponse>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::CheckSector >::value();
  }
  static const char* value(const ::tku_msgs::CheckSectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TKU_MSGS_MESSAGE_CHECKSECTOR_H
