// Generated by gencpp from file tku_msgs/ColorArray.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_COLORARRAY_H
#define TKU_MSGS_MESSAGE_COLORARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tku_msgs/ColorData.h>

namespace tku_msgs
{
template <class ContainerAllocator>
struct ColorArray_
{
  typedef ColorArray_<ContainerAllocator> Type;

  ColorArray_()
    : cnt(0)
    , Colorarray()  {
    }
  ColorArray_(const ContainerAllocator& _alloc)
    : cnt(0)
    , Colorarray(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _cnt_type;
  _cnt_type cnt;

   typedef std::vector< ::tku_msgs::ColorData_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tku_msgs::ColorData_<ContainerAllocator> >> _Colorarray_type;
  _Colorarray_type Colorarray;





  typedef boost::shared_ptr< ::tku_msgs::ColorArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::ColorArray_<ContainerAllocator> const> ConstPtr;

}; // struct ColorArray_

typedef ::tku_msgs::ColorArray_<std::allocator<void> > ColorArray;

typedef boost::shared_ptr< ::tku_msgs::ColorArray > ColorArrayPtr;
typedef boost::shared_ptr< ::tku_msgs::ColorArray const> ColorArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::ColorArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::ColorArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::ColorArray_<ContainerAllocator1> & lhs, const ::tku_msgs::ColorArray_<ContainerAllocator2> & rhs)
{
  return lhs.cnt == rhs.cnt &&
    lhs.Colorarray == rhs.Colorarray;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::ColorArray_<ContainerAllocator1> & lhs, const ::tku_msgs::ColorArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::ColorArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::ColorArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::ColorArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::ColorArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::ColorArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::ColorArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::ColorArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9cb678902d3e5f54cc5645b0e01f2d9e";
  }

  static const char* value(const ::tku_msgs::ColorArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9cb678902d3e5f54ULL;
  static const uint64_t static_value2 = 0xcc5645b0e01f2d9eULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::ColorArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/ColorArray";
  }

  static const char* value(const ::tku_msgs::ColorArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::ColorArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 cnt\n"
"ColorData[] Colorarray\n"
"\n"
"================================================================================\n"
"MSG: tku_msgs/ColorData\n"
"int32 X\n"
"int32 Y\n"
"int32 XMin\n"
"int32 XMax\n"
"int32 YMin\n"
"int32 YMax\n"
"int32 Width\n"
"int32 Height\n"
"int32 size                                                 \n"
;
  }

  static const char* value(const ::tku_msgs::ColorArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::ColorArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cnt);
      stream.next(m.Colorarray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::ColorArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::ColorArray_<ContainerAllocator>& v)
  {
    s << indent << "cnt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cnt);
    s << indent << "Colorarray[]" << std::endl;
    for (size_t i = 0; i < v.Colorarray.size(); ++i)
    {
      s << indent << "  Colorarray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tku_msgs::ColorData_<ContainerAllocator> >::stream(s, indent + "    ", v.Colorarray[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_COLORARRAY_H
