// Generated by gencpp from file tku_msgs/Distance.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_DISTANCE_H
#define TKU_MSGS_MESSAGE_DISTANCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct Distance_
{
  typedef Distance_<ContainerAllocator> Type;

  Distance_()
    : x_dis(0)
    , y_dis(0)
    , dis(0)  {
    }
  Distance_(const ContainerAllocator& _alloc)
    : x_dis(0)
    , y_dis(0)
    , dis(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_dis_type;
  _x_dis_type x_dis;

   typedef int16_t _y_dis_type;
  _y_dis_type y_dis;

   typedef int16_t _dis_type;
  _dis_type dis;





  typedef boost::shared_ptr< ::tku_msgs::Distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::Distance_<ContainerAllocator> const> ConstPtr;

}; // struct Distance_

typedef ::tku_msgs::Distance_<std::allocator<void> > Distance;

typedef boost::shared_ptr< ::tku_msgs::Distance > DistancePtr;
typedef boost::shared_ptr< ::tku_msgs::Distance const> DistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::Distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::Distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::Distance_<ContainerAllocator1> & lhs, const ::tku_msgs::Distance_<ContainerAllocator2> & rhs)
{
  return lhs.x_dis == rhs.x_dis &&
    lhs.y_dis == rhs.y_dis &&
    lhs.dis == rhs.dis;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::Distance_<ContainerAllocator1> & lhs, const ::tku_msgs::Distance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::Distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::Distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::Distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::Distance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3321358cdd898a39621fbe77e10211cf";
  }

  static const char* value(const ::tku_msgs::Distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3321358cdd898a39ULL;
  static const uint64_t static_value2 = 0x621fbe77e10211cfULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/Distance";
  }

  static const char* value(const ::tku_msgs::Distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x_dis\n"
"int16 y_dis\n"
"int16 dis\n"
;
  }

  static const char* value(const ::tku_msgs::Distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::Distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_dis);
      stream.next(m.y_dis);
      stream.next(m.dis);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::Distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::Distance_<ContainerAllocator>& v)
  {
    s << indent << "x_dis: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x_dis);
    s << indent << "y_dis: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y_dis);
    s << indent << "dis: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dis);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_DISTANCE_H
