// Generated by gencpp from file tku_msgs/FeaturePoint.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_FEATUREPOINT_H
#define TKU_MSGS_MESSAGE_FEATUREPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tku_msgs/Distance.h>

namespace tku_msgs
{
template <class ContainerAllocator>
struct FeaturePoint_
{
  typedef FeaturePoint_<ContainerAllocator> Type;

  FeaturePoint_()
    : feature_point()  {
    }
  FeaturePoint_(const ContainerAllocator& _alloc)
    : feature_point(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::tku_msgs::Distance_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tku_msgs::Distance_<ContainerAllocator> >> _feature_point_type;
  _feature_point_type feature_point;





  typedef boost::shared_ptr< ::tku_msgs::FeaturePoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::FeaturePoint_<ContainerAllocator> const> ConstPtr;

}; // struct FeaturePoint_

typedef ::tku_msgs::FeaturePoint_<std::allocator<void> > FeaturePoint;

typedef boost::shared_ptr< ::tku_msgs::FeaturePoint > FeaturePointPtr;
typedef boost::shared_ptr< ::tku_msgs::FeaturePoint const> FeaturePointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::FeaturePoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::FeaturePoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::FeaturePoint_<ContainerAllocator1> & lhs, const ::tku_msgs::FeaturePoint_<ContainerAllocator2> & rhs)
{
  return lhs.feature_point == rhs.feature_point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::FeaturePoint_<ContainerAllocator1> & lhs, const ::tku_msgs::FeaturePoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::FeaturePoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::FeaturePoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::FeaturePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::FeaturePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::FeaturePoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::FeaturePoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::FeaturePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3a2ec9f1de9fdc200c3e7d29ae54450";
  }

  static const char* value(const ::tku_msgs::FeaturePoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3a2ec9f1de9fdc2ULL;
  static const uint64_t static_value2 = 0x00c3e7d29ae54450ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::FeaturePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/FeaturePoint";
  }

  static const char* value(const ::tku_msgs::FeaturePoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::FeaturePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Distance[] feature_point\n"
"\n"
"================================================================================\n"
"MSG: tku_msgs/Distance\n"
"int16 x_dis\n"
"int16 y_dis\n"
"int16 dis\n"
;
  }

  static const char* value(const ::tku_msgs::FeaturePoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::FeaturePoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feature_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FeaturePoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::FeaturePoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::FeaturePoint_<ContainerAllocator>& v)
  {
    s << indent << "feature_point[]" << std::endl;
    for (size_t i = 0; i < v.feature_point.size(); ++i)
    {
      s << indent << "  feature_point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tku_msgs::Distance_<ContainerAllocator> >::stream(s, indent + "    ", v.feature_point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_FEATUREPOINT_H
