// Generated by gencpp from file tku_msgs/HSVInfoRequest.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_HSVINFOREQUEST_H
#define TKU_MSGS_MESSAGE_HSVINFOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct HSVInfoRequest_
{
  typedef HSVInfoRequest_<ContainerAllocator> Type;

  HSVInfoRequest_()
    : ColorLabel(0)  {
    }
  HSVInfoRequest_(const ContainerAllocator& _alloc)
    : ColorLabel(0)  {
  (void)_alloc;
    }



   typedef int16_t _ColorLabel_type;
  _ColorLabel_type ColorLabel;





  typedef boost::shared_ptr< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HSVInfoRequest_

typedef ::tku_msgs::HSVInfoRequest_<std::allocator<void> > HSVInfoRequest;

typedef boost::shared_ptr< ::tku_msgs::HSVInfoRequest > HSVInfoRequestPtr;
typedef boost::shared_ptr< ::tku_msgs::HSVInfoRequest const> HSVInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::HSVInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::HSVInfoRequest_<ContainerAllocator1> & lhs, const ::tku_msgs::HSVInfoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ColorLabel == rhs.ColorLabel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::HSVInfoRequest_<ContainerAllocator1> & lhs, const ::tku_msgs::HSVInfoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18a4a835e57bd84ea6cde968f2770df8";
  }

  static const char* value(const ::tku_msgs::HSVInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18a4a835e57bd84eULL;
  static const uint64_t static_value2 = 0xa6cde968f2770df8ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/HSVInfoRequest";
  }

  static const char* value(const ::tku_msgs::HSVInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 ColorLabel\n"
;
  }

  static const char* value(const ::tku_msgs::HSVInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ColorLabel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HSVInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::HSVInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::HSVInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "ColorLabel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ColorLabel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_HSVINFOREQUEST_H
