// Generated by gencpp from file tku_msgs/HSVInfo.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_HSVINFO_H
#define TKU_MSGS_MESSAGE_HSVINFO_H

#include <ros/service_traits.h>


#include <tku_msgs/HSVInfoRequest.h>
#include <tku_msgs/HSVInfoResponse.h>


namespace tku_msgs
{

struct HSVInfo
{

typedef HSVInfoRequest Request;
typedef HSVInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HSVInfo
} // namespace tku_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tku_msgs::HSVInfo > {
  static const char* value()
  {
    return "e67cb823b89b43c54c3cf2f810ee06c4";
  }

  static const char* value(const ::tku_msgs::HSVInfo&) { return value(); }
};

template<>
struct DataType< ::tku_msgs::HSVInfo > {
  static const char* value()
  {
    return "tku_msgs/HSVInfo";
  }

  static const char* value(const ::tku_msgs::HSVInfo&) { return value(); }
};


// service_traits::MD5Sum< ::tku_msgs::HSVInfoRequest> should match
// service_traits::MD5Sum< ::tku_msgs::HSVInfo >
template<>
struct MD5Sum< ::tku_msgs::HSVInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::HSVInfo >::value();
  }
  static const char* value(const ::tku_msgs::HSVInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::HSVInfoRequest> should match
// service_traits::DataType< ::tku_msgs::HSVInfo >
template<>
struct DataType< ::tku_msgs::HSVInfoRequest>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::HSVInfo >::value();
  }
  static const char* value(const ::tku_msgs::HSVInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tku_msgs::HSVInfoResponse> should match
// service_traits::MD5Sum< ::tku_msgs::HSVInfo >
template<>
struct MD5Sum< ::tku_msgs::HSVInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::HSVInfo >::value();
  }
  static const char* value(const ::tku_msgs::HSVInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::HSVInfoResponse> should match
// service_traits::DataType< ::tku_msgs::HSVInfo >
template<>
struct DataType< ::tku_msgs::HSVInfoResponse>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::HSVInfo >::value();
  }
  static const char* value(const ::tku_msgs::HSVInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TKU_MSGS_MESSAGE_HSVINFO_H
