// Generated by gencpp from file tku_msgs/IKinfoResponse.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_IKINFORESPONSE_H
#define TKU_MSGS_MESSAGE_IKINFORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct IKinfoResponse_
{
  typedef IKinfoResponse_<ContainerAllocator> Type;

  IKinfoResponse_()
    : SentData(false)  {
    }
  IKinfoResponse_(const ContainerAllocator& _alloc)
    : SentData(false)  {
  (void)_alloc;
    }



   typedef uint8_t _SentData_type;
  _SentData_type SentData;





  typedef boost::shared_ptr< ::tku_msgs::IKinfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::IKinfoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IKinfoResponse_

typedef ::tku_msgs::IKinfoResponse_<std::allocator<void> > IKinfoResponse;

typedef boost::shared_ptr< ::tku_msgs::IKinfoResponse > IKinfoResponsePtr;
typedef boost::shared_ptr< ::tku_msgs::IKinfoResponse const> IKinfoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::IKinfoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::IKinfoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::IKinfoResponse_<ContainerAllocator1> & lhs, const ::tku_msgs::IKinfoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.SentData == rhs.SentData;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::IKinfoResponse_<ContainerAllocator1> & lhs, const ::tku_msgs::IKinfoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::IKinfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::IKinfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::IKinfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::IKinfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::IKinfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::IKinfoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::IKinfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08fa172385d786afe021a46a156e44f4";
  }

  static const char* value(const ::tku_msgs::IKinfoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08fa172385d786afULL;
  static const uint64_t static_value2 = 0xe021a46a156e44f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::IKinfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/IKinfoResponse";
  }

  static const char* value(const ::tku_msgs::IKinfoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::IKinfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool SentData\n"
"\n"
;
  }

  static const char* value(const ::tku_msgs::IKinfoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::IKinfoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SentData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IKinfoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::IKinfoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::IKinfoResponse_<ContainerAllocator>& v)
  {
    s << indent << "SentData: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.SentData);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_IKINFORESPONSE_H
