// Generated by gencpp from file tku_msgs/InterfaceSend2Sector.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_INTERFACESEND2SECTOR_H
#define TKU_MSGS_MESSAGE_INTERFACESEND2SECTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct InterfaceSend2Sector_
{
  typedef InterfaceSend2Sector_<ContainerAllocator> Type;

  InterfaceSend2Sector_()
    : Package(0)
    , sectorname()  {
    }
  InterfaceSend2Sector_(const ContainerAllocator& _alloc)
    : Package(0)
    , sectorname(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _Package_type;
  _Package_type Package;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sectorname_type;
  _sectorname_type sectorname;





  typedef boost::shared_ptr< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> const> ConstPtr;

}; // struct InterfaceSend2Sector_

typedef ::tku_msgs::InterfaceSend2Sector_<std::allocator<void> > InterfaceSend2Sector;

typedef boost::shared_ptr< ::tku_msgs::InterfaceSend2Sector > InterfaceSend2SectorPtr;
typedef boost::shared_ptr< ::tku_msgs::InterfaceSend2Sector const> InterfaceSend2SectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator1> & lhs, const ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator2> & rhs)
{
  return lhs.Package == rhs.Package &&
    lhs.sectorname == rhs.sectorname;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator1> & lhs, const ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "259b9b823a54b61e8ccd5c2bcb938816";
  }

  static const char* value(const ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x259b9b823a54b61eULL;
  static const uint64_t static_value2 = 0x8ccd5c2bcb938816ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/InterfaceSend2Sector";
  }

  static const char* value(const ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 Package\n"
"string sectorname\n"
;
  }

  static const char* value(const ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Package);
      stream.next(m.sectorname);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterfaceSend2Sector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::InterfaceSend2Sector_<ContainerAllocator>& v)
  {
    s << indent << "Package: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Package);
    s << indent << "sectorname: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sectorname);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_INTERFACESEND2SECTOR_H
