// Generated by gencpp from file tku_msgs/ObjectInfo.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_OBJECTINFO_H
#define TKU_MSGS_MESSAGE_OBJECTINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tku_msgs/WitchData.h>
#include <tku_msgs/WitchData.h>

namespace tku_msgs
{
template <class ContainerAllocator>
struct ObjectInfo_
{
  typedef ObjectInfo_<ContainerAllocator> Type;

  ObjectInfo_()
    : name()
    , x(0.0)
    , y(0.0)
    , exist_flag(false)
    , theta()
    , dist()  {
    }
  ObjectInfo_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , x(0.0)
    , y(0.0)
    , exist_flag(false)
    , theta(_alloc)
    , dist(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef uint8_t _exist_flag_type;
  _exist_flag_type exist_flag;

   typedef  ::tku_msgs::WitchData_<ContainerAllocator>  _theta_type;
  _theta_type theta;

   typedef  ::tku_msgs::WitchData_<ContainerAllocator>  _dist_type;
  _dist_type dist;





  typedef boost::shared_ptr< ::tku_msgs::ObjectInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::ObjectInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectInfo_

typedef ::tku_msgs::ObjectInfo_<std::allocator<void> > ObjectInfo;

typedef boost::shared_ptr< ::tku_msgs::ObjectInfo > ObjectInfoPtr;
typedef boost::shared_ptr< ::tku_msgs::ObjectInfo const> ObjectInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::ObjectInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::ObjectInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::ObjectInfo_<ContainerAllocator1> & lhs, const ::tku_msgs::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.exist_flag == rhs.exist_flag &&
    lhs.theta == rhs.theta &&
    lhs.dist == rhs.dist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::ObjectInfo_<ContainerAllocator1> & lhs, const ::tku_msgs::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::ObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::ObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::ObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::ObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::ObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::ObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47a2b9ccd08f45a927e72a0d6f89a035";
  }

  static const char* value(const ::tku_msgs::ObjectInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47a2b9ccd08f45a9ULL;
  static const uint64_t static_value2 = 0x27e72a0d6f89a035ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/ObjectInfo";
  }

  static const char* value(const ::tku_msgs::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float32 x\n"
"float32 y\n"
"bool exist_flag\n"
"WitchData theta\n"
"WitchData dist\n"
"\n"
"================================================================================\n"
"MSG: tku_msgs/WitchData\n"
"float32 local\n"
"float32 global\n"
;
  }

  static const char* value(const ::tku_msgs::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::ObjectInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.exist_flag);
      stream.next(m.theta);
      stream.next(m.dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::ObjectInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::ObjectInfo_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "exist_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.exist_flag);
    s << indent << "theta: ";
    s << std::endl;
    Printer< ::tku_msgs::WitchData_<ContainerAllocator> >::stream(s, indent + "  ", v.theta);
    s << indent << "dist: ";
    s << std::endl;
    Printer< ::tku_msgs::WitchData_<ContainerAllocator> >::stream(s, indent + "  ", v.dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_OBJECTINFO_H
