// Generated by gencpp from file tku_msgs/SandHandSpeed.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_SANDHANDSPEED_H
#define TKU_MSGS_MESSAGE_SANDHANDSPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct SandHandSpeed_
{
  typedef SandHandSpeed_<ContainerAllocator> Type;

  SandHandSpeed_()
    : sector(0)
    , speed(0)  {
    }
  SandHandSpeed_(const ContainerAllocator& _alloc)
    : sector(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef int16_t _sector_type;
  _sector_type sector;

   typedef int16_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::tku_msgs::SandHandSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::SandHandSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct SandHandSpeed_

typedef ::tku_msgs::SandHandSpeed_<std::allocator<void> > SandHandSpeed;

typedef boost::shared_ptr< ::tku_msgs::SandHandSpeed > SandHandSpeedPtr;
typedef boost::shared_ptr< ::tku_msgs::SandHandSpeed const> SandHandSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::SandHandSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::SandHandSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::SandHandSpeed_<ContainerAllocator1> & lhs, const ::tku_msgs::SandHandSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.sector == rhs.sector &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::SandHandSpeed_<ContainerAllocator1> & lhs, const ::tku_msgs::SandHandSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::SandHandSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::SandHandSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::SandHandSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::SandHandSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::SandHandSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::SandHandSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::SandHandSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2d5ef17ed061f55340a6ac0fd02ec93";
  }

  static const char* value(const ::tku_msgs::SandHandSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2d5ef17ed061f55ULL;
  static const uint64_t static_value2 = 0x340a6ac0fd02ec93ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::SandHandSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/SandHandSpeed";
  }

  static const char* value(const ::tku_msgs::SandHandSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::SandHandSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 sector\n"
"int16 speed\n"
;
  }

  static const char* value(const ::tku_msgs::SandHandSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::SandHandSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sector);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SandHandSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::SandHandSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::SandHandSpeed_<ContainerAllocator>& v)
  {
    s << indent << "sector: ";
    Printer<int16_t>::stream(s, indent + "  ", v.sector);
    s << indent << "speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_SANDHANDSPEED_H
