// Generated by gencpp from file tku_msgs/SetRobotPos.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_SETROBOTPOS_H
#define TKU_MSGS_MESSAGE_SETROBOTPOS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct SetRobotPos_
{
  typedef SetRobotPos_<ContainerAllocator> Type;

  SetRobotPos_()
    : number(0)
    , x(0)
    , y(0)
    , dir(0)  {
    }
  SetRobotPos_(const ContainerAllocator& _alloc)
    : number(0)
    , x(0)
    , y(0)
    , dir(0)  {
  (void)_alloc;
    }



   typedef int16_t _number_type;
  _number_type number;

   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef int16_t _dir_type;
  _dir_type dir;





  typedef boost::shared_ptr< ::tku_msgs::SetRobotPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::SetRobotPos_<ContainerAllocator> const> ConstPtr;

}; // struct SetRobotPos_

typedef ::tku_msgs::SetRobotPos_<std::allocator<void> > SetRobotPos;

typedef boost::shared_ptr< ::tku_msgs::SetRobotPos > SetRobotPosPtr;
typedef boost::shared_ptr< ::tku_msgs::SetRobotPos const> SetRobotPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::SetRobotPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::SetRobotPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::SetRobotPos_<ContainerAllocator1> & lhs, const ::tku_msgs::SetRobotPos_<ContainerAllocator2> & rhs)
{
  return lhs.number == rhs.number &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.dir == rhs.dir;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::SetRobotPos_<ContainerAllocator1> & lhs, const ::tku_msgs::SetRobotPos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::SetRobotPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::SetRobotPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::SetRobotPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::SetRobotPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::SetRobotPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::SetRobotPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::SetRobotPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19f4baebbc12c880780ca548bf4b0c0b";
  }

  static const char* value(const ::tku_msgs::SetRobotPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19f4baebbc12c880ULL;
  static const uint64_t static_value2 = 0x780ca548bf4b0c0bULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::SetRobotPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/SetRobotPos";
  }

  static const char* value(const ::tku_msgs::SetRobotPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::SetRobotPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 number\n"
"int16 x\n"
"int16 y\n"
"int16 dir\n"
;
  }

  static const char* value(const ::tku_msgs::SetRobotPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::SetRobotPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRobotPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::SetRobotPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::SetRobotPos_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int16_t>::stream(s, indent + "  ", v.number);
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "dir: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_SETROBOTPOS_H
