// Generated by gencpp from file tku_msgs/WalkingGaitParameterRequest.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_WALKINGGAITPARAMETERREQUEST_H
#define TKU_MSGS_MESSAGE_WALKINGGAITPARAMETERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct WalkingGaitParameterRequest_
{
  typedef WalkingGaitParameterRequest_<ContainerAllocator> Type;

  WalkingGaitParameterRequest_()
    : mode(0)  {
    }
  WalkingGaitParameterRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WalkingGaitParameterRequest_

typedef ::tku_msgs::WalkingGaitParameterRequest_<std::allocator<void> > WalkingGaitParameterRequest;

typedef boost::shared_ptr< ::tku_msgs::WalkingGaitParameterRequest > WalkingGaitParameterRequestPtr;
typedef boost::shared_ptr< ::tku_msgs::WalkingGaitParameterRequest const> WalkingGaitParameterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator1> & lhs, const ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator1> & lhs, const ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff63f6ea3c3e9b7504b2cb3ee0a09d92";
  }

  static const char* value(const ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff63f6ea3c3e9b75ULL;
  static const uint64_t static_value2 = 0x04b2cb3ee0a09d92ULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/WalkingGaitParameterRequest";
  }

  static const char* value(const ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mode\n"
;
  }

  static const char* value(const ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WalkingGaitParameterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::WalkingGaitParameterRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_WALKINGGAITPARAMETERREQUEST_H
