// Generated by gencpp from file tku_msgs/WalkingGaitParameter.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_WALKINGGAITPARAMETER_H
#define TKU_MSGS_MESSAGE_WALKINGGAITPARAMETER_H

#include <ros/service_traits.h>


#include <tku_msgs/WalkingGaitParameterRequest.h>
#include <tku_msgs/WalkingGaitParameterResponse.h>


namespace tku_msgs
{

struct WalkingGaitParameter
{

typedef WalkingGaitParameterRequest Request;
typedef WalkingGaitParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WalkingGaitParameter
} // namespace tku_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tku_msgs::WalkingGaitParameter > {
  static const char* value()
  {
    return "1107a0c42506a0ca24378ebf4291f80a";
  }

  static const char* value(const ::tku_msgs::WalkingGaitParameter&) { return value(); }
};

template<>
struct DataType< ::tku_msgs::WalkingGaitParameter > {
  static const char* value()
  {
    return "tku_msgs/WalkingGaitParameter";
  }

  static const char* value(const ::tku_msgs::WalkingGaitParameter&) { return value(); }
};


// service_traits::MD5Sum< ::tku_msgs::WalkingGaitParameterRequest> should match
// service_traits::MD5Sum< ::tku_msgs::WalkingGaitParameter >
template<>
struct MD5Sum< ::tku_msgs::WalkingGaitParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::WalkingGaitParameter >::value();
  }
  static const char* value(const ::tku_msgs::WalkingGaitParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::WalkingGaitParameterRequest> should match
// service_traits::DataType< ::tku_msgs::WalkingGaitParameter >
template<>
struct DataType< ::tku_msgs::WalkingGaitParameterRequest>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::WalkingGaitParameter >::value();
  }
  static const char* value(const ::tku_msgs::WalkingGaitParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tku_msgs::WalkingGaitParameterResponse> should match
// service_traits::MD5Sum< ::tku_msgs::WalkingGaitParameter >
template<>
struct MD5Sum< ::tku_msgs::WalkingGaitParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tku_msgs::WalkingGaitParameter >::value();
  }
  static const char* value(const ::tku_msgs::WalkingGaitParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tku_msgs::WalkingGaitParameterResponse> should match
// service_traits::DataType< ::tku_msgs::WalkingGaitParameter >
template<>
struct DataType< ::tku_msgs::WalkingGaitParameterResponse>
{
  static const char* value()
  {
    return DataType< ::tku_msgs::WalkingGaitParameter >::value();
  }
  static const char* value(const ::tku_msgs::WalkingGaitParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TKU_MSGS_MESSAGE_WALKINGGAITPARAMETER_H
