// Generated by gencpp from file tku_msgs/WitchData.msg
// DO NOT EDIT!


#ifndef TKU_MSGS_MESSAGE_WITCHDATA_H
#define TKU_MSGS_MESSAGE_WITCHDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tku_msgs
{
template <class ContainerAllocator>
struct WitchData_
{
  typedef WitchData_<ContainerAllocator> Type;

  WitchData_()
    : local(0.0)
    , global(0.0)  {
    }
  WitchData_(const ContainerAllocator& _alloc)
    : local(0.0)
    , global(0.0)  {
  (void)_alloc;
    }



   typedef float _local_type;
  _local_type local;

   typedef float _global_type;
  _global_type global;





  typedef boost::shared_ptr< ::tku_msgs::WitchData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tku_msgs::WitchData_<ContainerAllocator> const> ConstPtr;

}; // struct WitchData_

typedef ::tku_msgs::WitchData_<std::allocator<void> > WitchData;

typedef boost::shared_ptr< ::tku_msgs::WitchData > WitchDataPtr;
typedef boost::shared_ptr< ::tku_msgs::WitchData const> WitchDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tku_msgs::WitchData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tku_msgs::WitchData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tku_msgs::WitchData_<ContainerAllocator1> & lhs, const ::tku_msgs::WitchData_<ContainerAllocator2> & rhs)
{
  return lhs.local == rhs.local &&
    lhs.global == rhs.global;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tku_msgs::WitchData_<ContainerAllocator1> & lhs, const ::tku_msgs::WitchData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tku_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::WitchData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tku_msgs::WitchData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::WitchData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tku_msgs::WitchData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::WitchData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tku_msgs::WitchData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tku_msgs::WitchData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c4765c233d983bd19b05cf6077eb24f";
  }

  static const char* value(const ::tku_msgs::WitchData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c4765c233d983bdULL;
  static const uint64_t static_value2 = 0x19b05cf6077eb24fULL;
};

template<class ContainerAllocator>
struct DataType< ::tku_msgs::WitchData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tku_msgs/WitchData";
  }

  static const char* value(const ::tku_msgs::WitchData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tku_msgs::WitchData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 local\n"
"float32 global\n"
;
  }

  static const char* value(const ::tku_msgs::WitchData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tku_msgs::WitchData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.local);
      stream.next(m.global);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WitchData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tku_msgs::WitchData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tku_msgs::WitchData_<ContainerAllocator>& v)
  {
    s << indent << "local: ";
    Printer<float>::stream(s, indent + "  ", v.local);
    s << indent << "global: ";
    Printer<float>::stream(s, indent + "  ", v.global);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TKU_MSGS_MESSAGE_WITCHDATA_H
